## Tarea 1
Programa Experto en Inteligencia Artificial con Python  
ML3006 - Web Mining en Python  
Estudiante: Natalia Bonilla Villalobos.

<a id="menu"></a>

# Menú
- [Ejercicio 1](#ej1)
- [Ejercicio 2](#ej2)

In [1]:
# !pip install lxml
# !pip install html5lib
# !pip install beautifulsoup4

In [6]:
from urllib.request import Request, urlopen
from bs4 import BeautifulSoup
from io import StringIO
import pandas as pd
import numpy as np

<a id="ej1"></a>
# Ejercicio 1

[50 puntos] Extracción de datos de cantones de Costa Rica  

En este ejercicio deberá extraer información sobre los cantones de Costa Rica desde Wikipedia. Visite: https://es.wikipedia.org/wiki/Anexo:Cantones_de_Costa_Rica  

Su tarea consiste en:

- a) [15 puntos] Descargar la página y extraer sus tablas HTML utilizando `requests` y `pandas` (o `BeautifulSoup`, si fuera necesario).  
**Pista**: Use `pd.read_html()` para extraer tablas HTML. Busque tablas con la clase CSS wikitable.
- b) [20 puntos] Identificar y extraer la tabla principal que contiene la información de los cantones. La tabla final debe incluir, como mínimo, columnas equivalentes a provincia, cantón, ciudad cabecera, año de creación, área y población.
**Pista**: No todas las tablas son útiles. Implemente una función que verifique si una tabla contiene las columnas esperadas (busque palabras clave como cantón, provincia).
- c) [10 puntos] Realizar limpieza básica de los datos: eliminar filas completamente vacías, normalizar nombres de columnas y dejar la tabla lista para análisis en pandas.
- d) [5 puntos] Guardar el resultado final en un archivo CSV llamado `cantones_cr.csv`.
  
Notas importantes:
- Use headers HTTP apropiados para evitar bloqueos del servidor.
- La tabla resultante debe tener aproximadamente 80+ filas (cantones).
- Maneje posibles excepciones y errores de conexión.
- Entregue una solución reproducible: el código debe permitir regenerar el CSV a partir de la página indicada.

[↑ Volver al Menú](#menu)

## Parte 1
- a) [15 puntos] Descargar la página y extraer sus tablas HTML utilizando `requests` y `pandas` (o `BeautifulSoup`, si fuera necesario).  

    **Pista:** Use `pd.read_html()` para extraer tablas HTML. Busque tablas con la clase CSS wikitable.

In [7]:
url = 'https://es.wikipedia.org/wiki/Anexo:Cantones_de_Costa_Rica'
req = Request(url, headers={'User-Agent': 'Mozilla/5.0'})

webpage = urlopen(req).read()
# convertir bytes -> texto usando UTF-8
html = webpage.decode("utf-8")

pagina = BeautifulSoup(webpage, 'html.parser')
print(pagina.title.string)

Anexo:Cantones de Costa Rica - Wikipedia, la enciclopedia libre

## Parte 2
- b) [20 puntos] Identificar y extraer la tabla principal que contiene la información de los cantones. La tabla final debe incluir, como mínimo, columnas equivalentes a provincia, cantón, ciudad cabecera, año de creación, área y población.

    **Pista:** No todas las tablas son útiles. Implemente una función que verifique si
una tabla contiene las columnas esperadas (busque palabras clave como cantón,
provincia).

In [10]:
# table class=wikitable sortable jquery-tablesorter
# Provincia, Canton, Ciudad Cabecera, año de creación, área y población
etqTable = pagina.find("table", {'class':'wikitable sortable'})
# print(etqTable)
print(etqTable.text.strip()[:500])

Provincia

Cantón

CiudadCabecera

Año decreación

Área(km²)

Altitud(m.s.n.m)

Población

IDH2020

Alcalde 2024-2028


Est. 2022

Est. Dens. 2022

Censo 2011

Partido

Nombre


San José San José



Cantón de San José San José

San José

1848

44,62

1137

352 381

7897,38

288 054

0,758

 PJSJ

Luis Diego Miranda Méndez




Cantón de Escazú Escazú

Escazú

1848

34,53

1129

71 500

2070,66

56 509

0,867

 PNG

Orlando Esteban Umaña Umaña




Cantón de Desamparados Desamparados

Desamparados

In [449]:
tablas = pd.read_html(StringIO(html))
tablas

[   Provincia                                           Cantón                \
    Provincia                                           Cantón      Cantón.1
 0   San José                                              NaN      San José
 1   San José                                              NaN        Escazú
 2   San José                                              NaN  Desamparados
 3   San José                                              NaN      Puriscal
 4   San José                                              NaN       Tarrazú
 ..       ...                                              ...           ...
 79     Limón     [[Archivo:|30px|Escudo de Cantón de Pococí]]        Pococí
 80     Limón  [[Archivo:|30px|Escudo de Cantón de Siquirres]]     Siquirres
 81     Limón  [[Archivo:|30px|Escudo de Cantón de Talamanca]]     Talamanca
 82     Limón     [[Archivo:|30px|Escudo de Cantón de Matina]]        Matina
 83     Limón    [[Archivo:|30px|Escudo de Cantón de Guácimo]]       Guácimo

    Ciudad Cabecera Año de creación Área (km²) Altitud (m.s.n.m) Población  \
    Ciudad Cabecera Año de creación Área (km²) Altitud (m.s.n.m) Est. 2022
 0         San José            1848       4462              1137   352 381
 1           Escazú            1848       3453              1129    71 500
 2     Desamparados            1862      11889              1270   223 226
 3         Santiago            1868      55504               945    38 525
 4       San Marcos            1868      29127              1471    17 810
 ..             ...             ...        ...               ...       ...
 79        Guápiles            1911     218817               134   146 320
 80       Siquirres            1911      85514               127    63 765
 81          Bribri            1969     279223                29    48 906
 82          Matina            1969       7704                13    45 329
 83         Guácimo            1971      80156                67    49 606

                               IDH 2020 Alcalde 2024-2028  \
    Est. Dens. 2022 Censo 2011 IDH 2020           Partido
 0           789738    288 054    758.0              PJSJ
 1           207066     56 509    867.0               PNG
 2           187758    208 411    743.0               PLN
 3             6941     33 004    755.0               PLN
 4             6115     16 280    668.0              PUSC
 ..             ...        ...      ...               ...
 79            6687    125 962    700.0                UP
 80            7457     56 786    723.0               PLN
 81            1752     30 712    601.0              PUSC
 82            5884     37 721    579.0              PUSC
 83            6189     41 266    676.0              PJSC


                             Nombre
 0        Luis Diego Miranda Méndez
 1      Orlando Esteban Umaña Umaña
 2   María Antonieta Naranjo Brenes
 3     Iris Cristina Arroyo Hererra
 4         Fernando Portuguez Parra
 ..                             ...
 79         Manuel Hernández Rivera
 80               Randal Black Reid
 81        Rugeli Morales Rodríguez
 82         Wálter Céspedes Salazar
 83           Beatriz Mora Valverde

 [84 rows x 13 columns],
                         0                                     1
 0  Control de autoridades  Proyectos Wikimedia  Datos: Q6173846]

In [451]:
def es_tabla_cantones(df):
    
    columnas = " ".join([str(c) for c in df.columns]).lower()
    
    if "provincia" in columnas and "cantón" in columnas:
        return True
    
    return False


tabla_cantones = None

for tabla in tablas:
    if es_tabla_cantones(tabla):
        tabla_cantones = tabla
        break

tabla_cantones.head()

  Provincia Cantón               Ciudad Cabecera Año de creación Área (km²)  \
  Provincia Cantón      Cantón.1 Ciudad Cabecera Año de creación Área (km²)
0  San José    NaN      San José        San José            1848       4462
1  San José    NaN        Escazú          Escazú            1848       3453
2  San José    NaN  Desamparados    Desamparados            1862      11889
3  San José    NaN      Puriscal        Santiago            1868      55504
4  San José    NaN       Tarrazú      San Marcos            1868      29127

  Altitud (m.s.n.m) Población                            IDH 2020  \
  Altitud (m.s.n.m) Est. 2022 Est. Dens. 2022 Censo 2011 IDH 2020
0              1137   352 381          789738    288 054    758.0
1              1129    71 500          207066     56 509    867.0
2              1270   223 226          187758    208 411    743.0
3               945    38 525            6941     33 004    755.0
4              1471    17 810            6115     16 280    668.0

  Alcalde 2024-2028
            Partido                          Nombre
0              PJSJ       Luis Diego Miranda Méndez
1               PNG     Orlando Esteban Umaña Umaña
2               PLN  María Antonieta Naranjo Brenes
3               PLN    Iris Cristina Arroyo Hererra
4              PUSC        Fernando Portuguez Parra

In [452]:
df = tabla_cantones.copy()
df.shape

(84, 13)

In [453]:
df.columns.tolist()

[('Provincia', 'Provincia'),
 ('Cantón', 'Cantón'),
 ('Cantón', 'Cantón.1'),
 ('Ciudad Cabecera', 'Ciudad Cabecera'),
 ('Año de creación', 'Año de creación'),
 ('Área (km²)', 'Área (km²)'),
 ('Altitud (m.s.n.m)', 'Altitud (m.s.n.m)'),
 ('Población', 'Est. 2022'),
 ('Población', 'Est. Dens. 2022'),
 ('Población', 'Censo 2011'),
 ('IDH 2020', 'IDH 2020'),
 ('Alcalde 2024-2028', 'Partido'),
 ('Alcalde 2024-2028', 'Nombre')]

In [454]:
df.columns = df.columns.get_level_values(1) # Aplanamos las columnas, eliminacion de multi-index
df.head(3)

,Provincia,Cantón,Cantón.1,Ciudad Cabecera,Año de creación,Área (km²),Altitud (m.s.n.m),Est. 2022,Est. Dens. 2022,Censo 2011,IDH 2020,Partido,Nombre
0,San José,NaN,San José,San José,1848,4462,1137,352 381,789738,288 054,758.0,PJSJ,Luis Diego Miranda Méndez
1,San José,NaN,Escazú,Escazú,1848,3453,1129,71 500,207066,56 509,867.0,PNG,Orlando Esteban Umaña Umaña
2,San José,NaN,Desamparados,Desamparados,1862,11889,1270,223 226,187758,208 411,743.0,PLN,María Antonieta Naranjo Brenes

In [455]:
# Eliminacion de columnas que no necesitamos
df = df.drop(columns=['Cantón', 'Altitud (m.s.n.m)','IDH 2020', 'Partido', 'Nombre', 'Est. Dens. 2022','Censo 2011'])
df.sample(5)

,Provincia,Cantón.1,Ciudad Cabecera,Año de creación,Área (km²),Est. 2022
33,Alajuela,Los Chiles,Los Chiles,1970,133271,34 701
37,Cartago,Paraíso,Paraíso,1848,477,65 941
80,Limón,Siquirres,Siquirres,1911,85514,63 765
47,Heredia,Santa Bárbara,Santa Bárbara,1882,521,39 133
14,San José,Montes de Oca,San Pedro,1915,1578,53 862

## Parte 3
- c) [10 puntos] Realizar limpieza básica de los datos: eliminar filas completamente vacías, normalizar nombres de columnas y dejar la tabla lista para análisis en pandas.

In [456]:
print(repr(df['Est. 2022'].iloc[0]))

'352\xa0381'

In [457]:
# limpiar espacios
df.columns = df.columns.str.strip()
df.head(3)

,Provincia,Cantón.1,Ciudad Cabecera,Año de creación,Área (km²),Est. 2022
0,San José,San José,San José,1848,4462,352 381
1,San José,Escazú,Escazú,1848,3453,71 500
2,San José,Desamparados,Desamparados,1862,11889,223 226

In [458]:
df = df.dropna(how="all")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Provincia        84 non-null     object
 1   Cantón.1         84 non-null     object
 2   Ciudad Cabecera  84 non-null     object
 3   Año de creación  84 non-null     int64
 4   Área (km²)       84 non-null     int64
 5   Est. 2022        84 non-null     object
dtypes: int64(2), object(4)
memory usage: 4.1+ KB

In [459]:
# Eliminacion de caracter espcial \xa0 entre numeros,
# se pasa a sting se eliminan espacios y luego se pasa a int
df['Est. 2022'] = (df['Est. 2022']
                   .astype(str)
                   .str.replace(r"\s+", "", regex=True)
                   .astype(int)
)
df

,Provincia,Cantón.1,Ciudad Cabecera,Año de creación,Área (km²),Est. 2022
0,San José,San José,San José,1848,4462,352381
1,San José,Escazú,Escazú,1848,3453,71500
2,San José,Desamparados,Desamparados,1862,11889,223226
3,San José,Puriscal,Santiago,1868,55504,38525
4,San José,Tarrazú,San Marcos,1868,29127,17810
...,...,...,...,...,...,...
79,Limón,Pococí,Guápiles,1911,218817,146320
80,Limón,Siquirres,Siquirres,1911,85514,63765
81,Limón,Talamanca,Bribri,1969,279223,48906
82,Limón,Matina,Matina,1969,7704,45329
83,Limón,Guácimo,Guácimo,1971,80156,49606

In [460]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Provincia        84 non-null     object
 1   Cantón.1         84 non-null     object
 2   Ciudad Cabecera  84 non-null     object
 3   Año de creación  84 non-null     int64
 4   Área (km²)       84 non-null     int64
 5   Est. 2022        84 non-null     int64
dtypes: int64(3), object(3)
memory usage: 4.1+ KB

In [461]:
# Renombrar columnas
df = df.rename(columns={'Cantón.1':'Cantón', 'Est. 2022':'Población'})

In [462]:
# Filas sin datos faltantes
df.isna().sum()

Provincia          0
Cantón             0
Ciudad Cabecera    0
Año de creación    0
Área (km²)         0
Población          0
dtype: int64

## Parte 4
- d) [5 puntos] Guardar el resultado final en un archivo CSV llamado `cantones_cr.csv`.

In [463]:
df.head(4)

,Provincia,Cantón,Ciudad Cabecera,Año de creación,Área (km²),Población
0,San José,San José,San José,1848,4462,352381
1,San José,Escazú,Escazú,1848,3453,71500
2,San José,Desamparados,Desamparados,1862,11889,223226
3,San José,Puriscal,Santiago,1868,55504,38525

In [464]:
df.to_csv("cantones_cr.csv", index=False, encoding="utf-8")

<a id="ej2"></a>
# Ejercicio 2

[50 puntos] Extracción de tipos de cambio del BCCR En este ejercicio deberá extraer los tipos de cambio de ventanilla del Banco Central
de Costa Rica. Visite: https://gee.bccr.fi.cr/IndicadoresEconomicos/Cuadros/frmConsultaTCVentanilla.aspx  

Su tarea consiste en:  

- a) [10 puntos] Descargar la página y extraer sus tablas utilizando requests y pandas.  
    **Pista**: Use `StringIO` con `pd.read_html()` para evitar warnings de futuras versiones.
- b) [15 puntos] Identificar y extraer la tabla principal de tipos de cambio que contiene las columnas: Tipo de entidad, Entidad autorizada, Compra, Venta, Diferencial cambiario y Última actualización.  
    **Pista**: Busque la tabla con más filas y al menos 6 columnas. Elimine la primera fila si contiene encabezados duplicados.
- c) [15 puntos] Realizar limpieza y procesamiento de datos:
    - Corregir problemas de encoding (caracteres como Ãľ, Ãś, etc.).
    - Llenar valores NaN en Tipo de entidad usando `ffill()`.
    - Convertir las columnas numéricas (Compra, Venta, Diferencial) dividiéndolas entre 100 para obtener el formato decimal correcto.  

    **Pista**: Los números vienen como enteros (p. ej., 49900) y deben convertirse a decimales (p. ej., 499.00).
- d) [10 puntos] Guardar el resultado final en un archivo CSV llamado `tc_ventanilla_bccr.csv` con codificación UTF-8.  

Notas importantes:
- Configure el encoding de la respuesta HTTP a utf-8.
- La tabla final debe contener aproximadamente 3540 entidades financieras.
- Todos los campos de Tipo de entidad deben estar completos (sin NaN).
- Use User-Agent apropiado en las cabeceras HTTP.
- Entregue una solución reproducible:

[↑ Volver al Menú](#menu)

## Parte 1
- a) [10 puntos] Descargar la página y extraer sus tablas utilizando requests y pandas.  
    **Pista**: Use `StringIO` con `pd.read_html()` para evitar warnings de futuras versiones.

In [4]:
# direccion de la pagina
src = 'https://gee.bccr.fi.cr/IndicadoresEconomicos/Cuadros/frmConsultaTCVentanilla.aspx'

# peticion 
req = Request(src, headers={'User-Agent': 'Mozilla/5.0'})
bccr_page = urlopen(req).read()

# convertir bytes -> texto usando UTF-8
html = bccr_page.decode("utf-8")

tipo_de_cambio_en_ventanila = BeautifulSoup(html, 'html.parser')
print(tipo_de_cambio_en_ventanila.title.string)

Tipo de cambio anunciado en ventanilla

In [5]:
# table id = 'DG'
etqTable = tipo_de_cambio_en_ventanila.find("table", {'id':'DG'})
print(etqTable.text.strip()[:500])

Tipo de EntidadEntidad AutorizadaCompraVentaDiferencial CambiarioÚltima Actualización

Bancos públicosBanco de Costa Rica                                                   458,00472,0014,0025/03/2026    01:23 p.m.

 Banco Nacional de Costa Rica                                          458,00472,0014,0025/03/2026    12:59 p.m.

 Banco Popular y de Desarrollo Comunal                                 457,00471,0014,0024/03/2026    02:10 p.m.

Bancos privadosBanco BAC San José S.A.

## Parte 2
- b) [15 puntos] Identificar y extraer la tabla principal de tipos de cambio que contiene las columnas: Tipo de entidad, Entidad autorizada, Compra, Venta, Diferencial cambiario y Última actualización.  

    **Pista**: Busque la tabla con más filas y al menos 6 columnas. Elimine la primera fila si contiene encabezados duplicados.

In [467]:
tabla = etqTable.find("table")

In [468]:
tipo_de_cambio = pd.read_html(StringIO(str(etqTable)))[0]

In [469]:
tipo_de_cambio.shape

(39, 6)

In [470]:
tipo_de_cambio.head(4)

,0,1,2,3,4,5
0,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
1,Bancos públicos,Banco de Costa Rica,46000,47400,1400,19/03/2026 08:32 p.m.
2,NaN,Banco Nacional de Costa Rica,45900,47300,1400,20/03/2026 08:35 a.m.
3,NaN,Banco Popular y de Desarrollo Comunal,46100,47500,1400,17/03/2026 01:37 p.m.

In [471]:
print(tipo_de_cambio.iloc[0,0].encode())

b'Tipo de Entidad'

In [472]:
tipo_de_cambio.isna().sum()

0    31
1     1
2     1
3     1
4     1
5     1
dtype: int64

In [473]:
# se copia el conjunto de datos original en otr avariable
df = tipo_de_cambio.copy()

In [474]:
# Se asignar la primera fila (0) como nombres de columnas
df.columns = df.iloc[0]
# Se liminar la primera fila (que ahora es el cabecera)
df = df.drop(df.index[0])
# Reiniciar el index para que comience en 0
df = df.reset_index(drop=True)

df.head(5)

,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
0,Bancos públicos,Banco de Costa Rica,46000,47400,1400,19/03/2026 08:32 p.m.
1,NaN,Banco Nacional de Costa Rica,45900,47300,1400,20/03/2026 08:35 a.m.
2,NaN,Banco Popular y de Desarrollo Comunal,46100,47500,1400,17/03/2026 01:37 p.m.
3,Bancos privados,Banco BAC San José S.A.,46000,47400,1400,20/03/2026 08:29 a.m.
4,NaN,Banco BCT S.A.,45700,47500,1800,19/03/2026 12:54 p.m.

In [475]:
df.shape, df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tipo de Entidad        7 non-null      object
 1   Entidad Autorizada     37 non-null     object
 2   Compra                 37 non-null     object
 3   Venta                  37 non-null     object
 4   Diferencial Cambiario  37 non-null     object
 5   Última Actualización   37 non-null     object
dtypes: object(6)
memory usage: 1.9+ KB

((38, 6), None)

## Parte 3
- c) [15 puntos] Realizar limpieza y procesamiento de datos:
    - Corregir problemas de encoding (caracteres como Ãľ, Ãś, etc.).
    - Llenar valores NaN en Tipo de entidad usando `ffill()`.
    - Convertir las columnas numéricas (Compra, Venta, Diferencial) dividiéndolas entre 100 para obtener el formato decimal correcto.  

    **Pista**: Los números vienen como enteros (p. ej., 49900) y deben convertirse a decimales (p. ej., 499.00).

In [476]:
df.columns

Index(['Tipo de Entidad', 'Entidad Autorizada', 'Compra', 'Venta',
       'Diferencial Cambiario', 'Última Actualización'],
      dtype='object', name=0)

In [477]:
# Revision de caracteres erroneos
def revision(df):
    for col in df:
        print(repr(df[col].iloc[0]))

revision(df)

'Bancos públicos'
'Banco de Costa Rica'
'46000'
'47400'
'1400'
'19/03/2026 08:32 p.m.'

In [478]:
df.tail(1)

,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
37,NaN,NaN,NaN,NaN,NaN,NaN

In [479]:
# Se elimina la ultima columna del data frame que esta vacia
# df = df.drop(df.tail(1).index)
df.drop(df.tail(1).index, inplace=True)

In [480]:
df.head(6)

,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
0,Bancos públicos,Banco de Costa Rica,46000,47400,1400,19/03/2026 08:32 p.m.
1,NaN,Banco Nacional de Costa Rica,45900,47300,1400,20/03/2026 08:35 a.m.
2,NaN,Banco Popular y de Desarrollo Comunal,46100,47500,1400,17/03/2026 01:37 p.m.
3,Bancos privados,Banco BAC San José S.A.,46000,47400,1400,20/03/2026 08:29 a.m.
4,NaN,Banco BCT S.A.,45700,47500,1800,19/03/2026 12:54 p.m.
5,NaN,Banco Cathay de Costa Rica S.A.,46000,47250,1250,19/03/2026 12:57 p.m.

In [481]:
# se rellenan los llenar valores faltantes propagando la última observación válida hacia adelante
df = df.ffill()

In [482]:
df.head(10)

,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
0,Bancos públicos,Banco de Costa Rica,46000,47400,1400,19/03/2026 08:32 p.m.
1,Bancos públicos,Banco Nacional de Costa Rica,45900,47300,1400,20/03/2026 08:35 a.m.
2,Bancos públicos,Banco Popular y de Desarrollo Comunal,46100,47500,1400,17/03/2026 01:37 p.m.
3,Bancos privados,Banco BAC San José S.A.,46000,47400,1400,20/03/2026 08:29 a.m.
4,Bancos privados,Banco BCT S.A.,45700,47500,1800,19/03/2026 12:54 p.m.
5,Bancos privados,Banco Cathay de Costa Rica S.A.,46000,47250,1250,19/03/2026 12:57 p.m.
6,Bancos privados,Banco CMB,45200,47600,2400,20/03/2026 09:34 a.m.
7,Bancos privados,Banco Davivienda (Costa Rica) S.A,45700,47500,1800,19/03/2026 02:01 p.m.
8,Bancos privados,Banco General (Costa Rica) S.A.,45700,47300,1600,19/03/2026 12:54 p.m.
9,Bancos privados,Banco Improsa S.A.,45800,47600,1800,17/03/2026 11:21 a.m.

In [483]:
df.isna().sum()

0
Tipo de Entidad          0
Entidad Autorizada       0
Compra                   0
Venta                    0
Diferencial Cambiario    0
Última Actualización     0
dtype: int64

In [484]:
# columnas de object -> float | Compra, Venta y Diferencial Cambiario
for col in df.iloc[:, 2:5].columns:  
    df[col] = df[col].astype(float)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Tipo de Entidad        37 non-null     object
 1   Entidad Autorizada     37 non-null     object
 2   Compra                 37 non-null     float64
 3   Venta                  37 non-null     float64
 4   Diferencial Cambiario  37 non-null     float64
 5   Última Actualización   37 non-null     object
dtypes: float64(3), object(3)
memory usage: 1.9+ KB

In [485]:
# for col in df2.iloc[:, 2:5].columns:        
#     df2[col] = (df2[col] / 100).round(2)

In [489]:
def to_decimal(df):        
    df2 = df.copy()
    df2.iloc[:, 2:5] = (df2.iloc[:, 2:5] / 100).round(2) # Compra, Venta y Diferencial Cambiario
    return df2

tc_ventanilla_bccr = to_decimal(df)
tc_ventanilla_bccr.head(5).sort_values('Compra', ascending=False)

,Tipo de Entidad,Entidad Autorizada,Compra,Venta,Diferencial Cambiario,Última Actualización
2,Bancos públicos,Banco Popular y de Desarrollo Comunal,461.0,475.0,14.0,17/03/2026 01:37 p.m.
0,Bancos públicos,Banco de Costa Rica,460.0,474.0,14.0,19/03/2026 08:32 p.m.
3,Bancos privados,Banco BAC San José S.A.,460.0,474.0,14.0,20/03/2026 08:29 a.m.
1,Bancos públicos,Banco Nacional de Costa Rica,459.0,473.0,14.0,20/03/2026 08:35 a.m.
4,Bancos privados,Banco BCT S.A.,457.0,475.0,18.0,19/03/2026 12:54 p.m.

## Parte 4 
- d) [10 puntos] Guardar el resultado final en un archivo CSV llamado `tc_ventanilla_bccr.csv` con codificación UTF-8.

In [487]:
tc_ventanilla_bccr.to_csv("tc_ventanilla_bccr.csv", index=False, encoding="utf-8")